// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS1iDgvxg_V55jI0zp88Bowr0LWWn8Di8',
    appId: '1:581493937880:web:911a47d07448aa706269ad',
    messagingSenderId: '581493937880',
    projectId: 'mynotes-isojb-f6529',
    authDomain: 'mynotes-isojb-f6529.firebaseapp.com',
    storageBucket: 'mynotes-isojb-f6529.appspot.com',
    measurementId: 'G-E8YX7RNHLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB37wnGI_3icjlVZwJOWyIP-jcOZ28IwIU',
    appId: '1:581493937880:android:6d7dd0cbcd17e5c26269ad',
    messagingSenderId: '581493937880',
    projectId: 'mynotes-isojb-f6529',
    storageBucket: 'mynotes-isojb-f6529.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFWsxOAWTXs9LxrepHX5yRS2IAcctXHvQ',
    appId: '1:581493937880:ios:2306479ec4c9a7f96269ad',
    messagingSenderId: '581493937880',
    projectId: 'mynotes-isojb-f6529',
    storageBucket: 'mynotes-isojb-f6529.appspot.com',
    iosClientId: '581493937880-s1cjtghlbi8mo1cf1s5lmikej3cl3859.apps.googleusercontent.com',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFWsxOAWTXs9LxrepHX5yRS2IAcctXHvQ',
    appId: '1:581493937880:ios:2306479ec4c9a7f96269ad',
    messagingSenderId: '581493937880',
    projectId: 'mynotes-isojb-f6529',
    storageBucket: 'mynotes-isojb-f6529.appspot.com',
    iosClientId: '581493937880-s1cjtghlbi8mo1cf1s5lmikej3cl3859.apps.googleusercontent.com',
    iosBundleId: 'com.example.project2',
  );
}
